dataset_name: concrete
dataset_display_name: 'Concrete'
dataset_type: 'ConcreteData'
openml_id: 4353
save_dir: datasets
num_workers: 8
batch_size: 512
layer_sizes: !!python/tuple [50, 50]
lr: 0.001
num_epochs: 1000
weight_decay: 0.01
max_rows: 500
