dataset_name: ct_slices
dataset_display_name: 'CT slices'
dataset_type: 'CTSlices'
save_dir: datasets
num_workers: 8
batch_size: 512
layer_sizes: !!python/tuple [50, 50]
lr: 0.001
num_epochs: 1000
weight_decay: 0.01
max_rows: 500
save_interval: 2000
