dataset_name: yacht_hydrodynamics
dataset_display_name: 'Yacht hydrodynamics'
dataset_type: 'OpenMLDataset'
openml_id: 40691
save_dir: datasets
num_workers: 8
batch_size: 512
layer_sizes: !!python/tuple [50, 50]
lr: 0.001
num_epochs: 1000
weight_decay: 0.01
max_rows: 300
